config/routes.rb
DevTroll::Application.routes.draw do

  resources :devs do 
    resources :trolls
  end

  

  root 'home#index'

  

end

app/models/dev.rb
class Dev < ActiveRecord::Base
	validates :name, presence: true
	has_many :trolls
end

app/models/troll.rb
class Troll < ActiveRecord::Base
	validates :text, presence: true
	belongs_to :dev
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController
  before_action :set_dev, only: [:show, :edit, :update, :destroy]

  # GET /devs
  # GET /devs.json
  def index
    @devs = Dev.all
  end

  # GET /devs/1
  # GET /devs/1.json
  def show
  end

  # GET /devs/new
  def new
    @dev = Dev.new
  end

  # GET /devs/1/edit
  def edit
  end

  # POST /devs
  # POST /devs.json
  def create
    @dev = Dev.new(dev_params)

    respond_to do |format|
      if @dev.save
        format.html { redirect_to @dev, notice: 'Dev was successfully created.' }
        format.json { render action: 'show', status: :created, location: @dev }
      else
        format.html { render action: 'new' }
        format.json { render json: @dev.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devs/1
  # PATCH/PUT /devs/1.json
  def update
    respond_to do |format|
      if @dev.update(dev_params)
        format.html { redirect_to @dev, notice: 'Dev was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @dev.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devs/1
  # DELETE /devs/1.json
  def destroy
    @dev.destroy
    respond_to do |format|
      format.html { redirect_to devs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dev
      @dev = Dev.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dev_params
      params.require(:dev).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController


def index
 rand_id = rand(Troll.first.id...Troll.last.id)
 rand_record = Troll.first(:conditions => [ "id >= ?", rand_id])
 @randomtroll = rand_record

 @alldevs = Dev.all

end


end

app/controllers/trolls_controller.rb
class TrollsController < ApplicationController
  before_action :set_troll, only: [:show, :edit, :update, :destroy]
  before_action :set_dev

  # GET /trolls
  # GET /trolls.json
  def index
    @trolls = Troll.where(dev: @dev)
  end

  # GET /trolls/1
  # GET /trolls/1.json
  def show
  end

  # GET /trolls/new
  def new
    @troll = Troll.new(dev: @dev)
  end

  # GET /trolls/1/edit
  def edit
  end

  # POST /trolls
  # POST /trolls.json
  def create
    @troll = Troll.new(troll_params.update(dev_id: @dev.id))
    respond_to do |format|
      if @troll.save
        format.html { redirect_to dev_troll_path(@dev, @troll), notice: 'Troll was successfully created.' }
        format.json { render action: 'show', status: :created, location: @troll }
      else
        format.html { render action: 'new' }
        format.json { render json: @troll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trolls/1
  # PATCH/PUT /trolls/1.json
  def update
    respond_to do |format|
      if @troll.update(troll_params)
        format.html { redirect_to dev_troll_path(@dev, @troll), notice: 'Troll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @troll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trolls/1
  # DELETE /trolls/1.json
  def destroy
    @troll.destroy
    respond_to do |format|
      format.html { redirect_to dev_trolls_path(@dev) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_troll
      @troll = Troll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def troll_params
      params.require(:troll).permit(:text)
    end

    def set_dev 
      @dev = Dev.find(params[:dev_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devs_helper.rb
module DevsHelper
end

app/helpers/trolls_helper.rb
module TrollsHelper
end

app/views/devs/_form.html.erb
<%= form_for(@dev) do |f| %>
  <% if @dev.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dev.errors.count, "error") %> prohibited this dev from being saved:</h2>

      <ul>
      <% @dev.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devs/edit.html.erb
<h1>Editing dev</h1>

<%= render 'form' %>

<%= link_to 'Show', @dev %> |
<%= link_to 'Back', devs_path %>

app/views/devs/index.html.erb
<h1>Listing devs</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @devs.each do |dev| %>
      <tr>
        <td><%= dev.name %></td>
        <td><%= link_to 'Show', dev %></td>
        <td><%= link_to 'Edit', edit_dev_path(dev) %></td>
        <td><%= link_to 'Destroy', dev, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dev', new_dev_path %>

app/views/devs/new.html.erb
<h1>New dev</h1>

<%= render 'form' %>

<%= link_to 'Back', devs_path %>

app/views/devs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dev.name %>
</p>

<%= link_to 'Edit', edit_dev_path(@dev) %> |
<%= link_to 'Back', devs_path %>

app/views/home/index.html.erb
	 <td><%= @randomtroll.text %></td>
	 <p>
	 <% @alldevs.each do |dev|%>
	 <a href=><%= dev.name %><% link_to dev_troll_path(dev, @random_troll) %></a>
	 <% end %>
	 </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevTroll</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trolls/_form.html.erb
<%= form_for [@dev, @troll] do |f| %>
  <% if @troll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@troll.errors.count, "error") %> prohibited this troll from being saved:</h2>

      <ul>
      <% @troll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trolls/edit.html.erb
<h1>Editing troll</h1>

<%= render 'form' %>

<%= link_to 'Show', [@dev, @troll] %> |
<%= link_to 'Back', dev_trolls_path(@dev)%>

app/views/trolls/index.html.erb
<h1>Listing trolls</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trolls.each do |troll| %>
      <tr>
        <td><%= troll.text %></td>
        <td><%= link_to 'Show', dev_troll_path(troll.dev, troll) %></td>
        <td><%= link_to 'Edit', edit_dev_troll_path(troll.dev, troll) %></td>
        <td><%= link_to 'Destroy', dev_troll_path(troll.dev, troll), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Troll', new_dev_troll_path(@dev) %>

app/views/trolls/new.html.erb
<h1>New troll</h1>

<%= render 'form' %>

<%= link_to 'Back', dev_trolls_path(@dev) %>

app/views/trolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @troll.text %>
</p>

<%= link_to 'Edit', edit_dev_troll_path(@dev, @troll) %> |
<%= link_to 'Back', dev_trolls_path(@dev) %>